name: Keep cache warm
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 1,6,11,16,21,27 * *'

permissions: {}

jobs:
  build:
    if: |
      vars.KEEP_CACHE_WARM || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      version: '999999'
      channel: stable
      origin: ${{ github.repository }}
      unix: false
      linux: false
      linux_armv7l: true
      musllinux: false
      macos: true
      windows: true
