name: Signature Tests
on:
  push:
    paths:
      - .github/workflows/signature-tests.yml
      - test/test_jsc/*.py
      - yt_dlp/extractor/youtube/jsc/**.js
      - yt_dlp/extractor/youtube/jsc/**.py
      - yt_dlp/extractor/youtube/pot/**.py
      - yt_dlp/utils/_jsruntime.py
  pull_request:
    paths:
      - .github/workflows/signature-tests.yml
      - test/test_jsc/*.py
      - yt_dlp/extractor/youtube/jsc/**.js
      - yt_dlp/extractor/youtube/jsc/**.py
      - yt_dlp/extractor/youtube/pot/**.py
      - yt_dlp/utils/_jsruntime.py
permissions:
  contents: read

concurrency:
  group: signature-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tests:
    name: Signature Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', pypy-3.11]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: '2.0.0'  # minimum supported version
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        # minimum supported version is 1.0.31 but earliest available Windows version is 1.1.0
        bun-version: ${{ (matrix.os == 'windows-latest' && '1.1.0') || '1.0.31' }}
    - name: Install Node
      uses: actions/setup-node@v6
      with:
        node-version: '20.0'  # minimum supported version
    - name: Install test requirements
      shell: bash
      run: |
        python ./devscripts/install_deps.py \
          --include test \
          --exclude brotli \
          --exclude brotlicffi \
          --exclude mutagen \
          --exclude pycryptodomex \
          --exclude websockets
    - name: Run tests
      timeout-minutes: 15
      shell: bash
      run: |
        python -m yt_dlp -v || true  # Print debug head
        python ./devscripts/run_tests.py test/test_jsc/
